# Docker Compose for local development
version: '3.8'

services:
  db:
    image: bitnami/postgresql:16.1.0
    container_name: ecommerce-db
    environment:
      POSTGRESQL_DATABASE: ecommerce
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: adminpass
      POSTGRESQL_POSTGRES_PASSWORD: adminpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
      - ../db/init.sql:/docker-entrypoint-initdb.d/custom-scripts/init.sql
    networks:
      - ecommerce-network

  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    environment:
      DATABASE_URL: postgresql://admin:adminpass@db:5432/ecommerce
      SECRET_KEY: devsecretkey
      FLASK_ENV: development
      FLASK_DEBUG: 1
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ../backend:/app
    networks:
      - ecommerce-network
    command: ["python", "app.py"]

  nginx:
    image: nginxinc/nginx-unprivileged:1.25-alpine
    container_name: ecommerce-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    networks:
      - ecommerce-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    environment:
      - REACT_APP_API_URL=http://localhost/api
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - ecommerce-network

volumes:
  postgres_data:

networks:
  ecommerce-network:
    driver: bridge
