apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-config
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
data:
  FLASK_ENV: {{ .Values.environment }}
  DATABASE_HOST: {{ include "ecommerce.fullname" . }}-postgresql
  DATABASE_PORT: "5432"
  DATABASE_NAME: {{ .Values.postgresql.auth.database }}
  REDIS_HOST: {{ include "ecommerce.fullname" . }}-redis
  REDIS_PORT: "6379"
  {{- if .Values.config.extraEnvVars }}
  {{- range $key, $value := .Values.config.extraEnvVars }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
