# Development environment values
environment: development

replicaCount: 1

image:
  backend:
    repository: ecommerce-backend
    tag: latest
    pullPolicy: IfNotPresent
  nginx:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ecommerce-dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  auth:
    database: ecommerce_dev
    username: ecommerce_user
    postgresPassword: dev_password123
  persistence:
    size: 5Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  auth:
    password: redis_dev_password
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

persistence:
  enabled: true

secrets:
  secretKey: dev-secret-key-12345
  jwtSecretKey: dev-jwt-secret-key-12345

config:
  extraEnvVars:
    DEBUG: "True"
    LOG_LEVEL: "DEBUG"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
